server:
  port: 8081

spring:
  application:
    name: subscriberPartition0

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: demo-consumer-partition-0
      client-id: demo-consumer-p0
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: true
logging:
  level:
    org.springframework.kafka: INFO
    org.apache.kafka: WARN


